// ================================================================
// Stub DataCenterDataSource — renders mock data so the map works
// out of the box. All 15 projects from the original screenshot are
// seeded with real lat/lon. Replace with your engine adapter when
// ready (see examples/EngineDataCenterAdapter.js for a template).
// ================================================================

const SEED_PROJECTS = [
  {
    id: 'stargate-abilene',
    name: 'Stargate Abilene',
    company: 'xAI / Oracle',
    category: 'stargate',
    status: 'under_construction',
    country: 'USA',
    countryName: 'United States',
    region: 'n_america',
    city: 'Abilene, TX',
    latitude: 32.45,
    longitude: -99.73,
    powerMw: 1200,
    investmentUsdM: 3500,
    expectedYear: 2026,
  },
  {
    id: 'colossus-memphis',
    name: 'Colossus Memphis',
    company: 'xAI',
    category: 'stargate',
    status: 'operational',
    country: 'USA',
    countryName: 'United States',
    region: 'n_america',
    city: 'Memphis, TN',
    latitude: 35.15,
    longitude: -90.05,
    powerMw: 800,
    investmentUsdM: 2000,
    expectedYear: 2025,
  },
  {
    id: 'mount-pleasant',
    name: 'Mount Pleasant',
    company: 'Microsoft',
    category: 'hyperscaler',
    status: 'under_construction',
    country: 'USA',
    countryName: 'United States',
    region: 'n_america',
    city: 'Mount Pleasant, WI',
    latitude: 42.72,
    longitude: -87.9,
    powerMw: 1000,
    investmentUsdM: 3300,
    expectedYear: 2026,
  },
  {
    id: 'hyperion-la',
    name: 'Hyperion LA',
    company: 'CoreWeave',
    category: 'neocloud',
    status: 'operational',
    country: 'USA',
    countryName: 'United States',
    region: 'n_america',
    city: 'Los Angeles, CA',
    latitude: 34.05,
    longitude: -118.24,
    powerMw: 600,
    investmentUsdM: 1200,
    expectedYear: 2025,
  },
  {
    id: 'project-eos',
    name: 'Project Eos',
    company: 'Meta',
    category: 'hyperscaler',
    status: 'under_construction',
    country: 'USA',
    countryName: 'United States',
    region: 'n_america',
    city: 'Richland Parish, LA',
    latitude: 32.42,
    longitude: -91.73,
    powerMw: 2000,
    investmentUsdM: 10000,
    expectedYear: 2027,
  },
  {
    id: 'wapato-creek',
    name: 'Wapato Creek',
    company: 'Amazon',
    category: 'hyperscaler',
    status: 'under_construction',
    country: 'USA',
    countryName: 'United States',
    region: 'n_america',
    city: 'Umatilla, OR',
    latitude: 45.92,
    longitude: -119.34,
    powerMw: 960,
    investmentUsdM: 2800,
    expectedYear: 2026,
  },
  {
    id: 'columbus',
    name: 'Columbus',
    company: 'Google',
    category: 'hyperscaler',
    status: 'operational',
    country: 'USA',
    countryName: 'United States',
    region: 'n_america',
    city: 'Columbus, OH',
    latitude: 39.96,
    longitude: -83.0,
    powerMw: 500,
    investmentUsdM: 1300,
    expectedYear: 2025,
  },
  {
    id: 'reno-technological',
    name: 'Reno Technological',
    company: 'NVIDIA',
    category: 'independent',
    status: 'operational',
    country: 'USA',
    countryName: 'United States',
    region: 'n_america',
    city: 'Reno, NV',
    latitude: 39.53,
    longitude: -119.81,
    powerMw: 150,
    investmentUsdM: 400,
    expectedYear: 2024,
  },
  {
    id: 'crusoe-energy',
    name: 'Crusoe Energy',
    company: 'Crusoe',
    category: 'independent',
    status: 'operational',
    country: 'USA',
    countryName: 'United States',
    region: 'n_america',
    city: 'Midland, TX',
    latitude: 32.0,
    longitude: -102.08,
    powerMw: 200,
    investmentUsdM: 500,
    expectedYear: 2024,
  },
  {
    id: 'glasgow-ai-hub',
    name: 'Glasgow AI Hub',
    company: 'Microsoft',
    category: 'hyperscaler',
    status: 'announced',
    country: 'GBR',
    countryName: 'United Kingdom',
    region: 'europe',
    city: 'Glasgow',
    latitude: 55.86,
    longitude: -4.25,
    powerMw: 150,
    investmentUsdM: 700,
    expectedYear: 2027,
  },
  {
    id: 'fujisawa',
    name: 'Fujisawa',
    company: 'NVIDIA',
    category: 'independent',
    status: 'under_construction',
    country: 'JPN',
    countryName: 'Japan',
    region: 'asia',
    city: 'Fujisawa',
    latitude: 35.34,
    longitude: 139.49,
    powerMw: 300,
    investmentUsdM: 900,
    expectedYear: 2026,
  },
  {
    id: 'abidjan-compute',
    name: 'Abidjan Compute',
    company: 'DataVolt',
    category: 'sovereign',
    status: 'under_construction',
    country: 'CIV',
    countryName: "Côte d'Ivoire",
    region: 'world',
    city: 'Abidjan',
    latitude: 5.36,
    longitude: -4.01,
    powerMw: 500,
    investmentUsdM: 1000,
    expectedYear: 2026,
  },
  {
    id: 'horizon-plains',
    name: 'Horizon Plains',
    company: 'Microsoft',
    category: 'hyperscaler',
    status: 'under_construction',
    country: 'USA',
    countryName: 'United States',
    region: 'n_america',
    city: 'San Antonio, TX',
    latitude: 29.42,
    longitude: -98.49,
    powerMw: 2000,
    investmentUsdM: 6000,
    expectedYear: 2027,
  },
  {
    id: 'odense-ai',
    name: 'Odense AI',
    company: 'Meta',
    category: 'hyperscaler',
    status: 'under_construction',
    country: 'DNK',
    countryName: 'Denmark',
    region: 'europe',
    city: 'Odense',
    latitude: 55.4,
    longitude: 10.39,
    powerMw: 200,
    investmentUsdM: 800,
    expectedYear: 2026,
  },
  {
    id: 'lulea-green',
    name: 'Luleå Green',
    company: 'NVIDIA',
    category: 'independent',
    status: 'operational',
    country: 'SWE',
    countryName: 'Sweden',
    region: 'europe',
    city: 'Luleå',
    latitude: 65.58,
    longitude: 22.16,
    powerMw: 500,
    investmentUsdM: 1100,
    expectedYear: 2025,
  },
  {
    id: 'stargate-uae',
    name: 'Stargate UAE',
    company: 'G42 / OpenAI',
    category: 'stargate',
    status: 'announced',
    country: 'ARE',
    countryName: 'United Arab Emirates',
    region: 'middle_east',
    city: 'Abu Dhabi',
    latitude: 24.45,
    longitude: 54.38,
    powerMw: 1000,
    investmentUsdM: 5000,
    expectedYear: 2027,
  },
  {
    id: 'neom-sovereign',
    name: 'NEOM Sovereign AI',
    company: 'Humain / HUMAIN',
    category: 'sovereign',
    status: 'announced',
    country: 'SAU',
    countryName: 'Saudi Arabia',
    region: 'middle_east',
    city: 'NEOM',
    latitude: 27.8,
    longitude: 35.2,
    powerMw: 500,
    investmentUsdM: 1800,
    expectedYear: 2027,
  },
];

export const stubDataCenterDataSource = {
  async fetchProjects({ signal: _signal }) {
    // Tiny delay to mimic real network
    await new Promise((r) => setTimeout(r, 150));
    return {
      projects: SEED_PROJECTS,
      fetchedAt: new Date().toISOString(),
    };
  },
};
